### PR TITLE
Test 01

### PR DESCRIPTION
**Pull request by jonasmarquezkc**
Test 01

### CODE REVIEW

**Comment by jonasmarquez** [comment]
Ran Plan for 2 projects:

1. project: `bucket` dir: `s3` workspace: `nonprod`
1. project: `instance` dir: `ec2` workspace: `nonprod`

### 1. project: `bucket` dir: `s3` workspace: `nonprod`
<details><summary>Show Output</summary>

```diff
PLANNING


[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Finding hashicorp/vault versions matching "3.5.0"...
- Finding hashicorp/aws versions matching "4.12.1"...
- Installing hashicorp/vault v3.5.0...
- Installed hashicorp/vault v3.5.0 (signed by HashiCorp)
- Installing hashicorp/aws v4.12.1...
- Installed hashicorp/aws v4.12.1 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket.s3-bucket will be created
+ resource "aws_s3_bucket" "s3-bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "test-terraform-atlantis-workflow-demo-02"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "Environment" = "nonprod"
          + "Name"        = "test-terraform-atlantis-workflow-demo-02"
        }
      + tags_all                    = {
          + "Environment" = "nonprod"
          + "Name"        = "test-terraform-atlantis-workflow-demo-02"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + cors_rule {
          + allowed_headers = (known after apply)
          + allowed_methods = (known after apply)
          + allowed_origins = (known after apply)
          + expose_headers  = (known after apply)
          + max_age_seconds = (known after apply)
        }

      + grant {
          + id          = (known after apply)
          + permissions = (known after apply)
          + type        = (known after apply)
          + uri         = (known after apply)
        }

      + lifecycle_rule {
          + abort_incomplete_multipart_upload_days = (known after apply)
          + enabled                                = (known after apply)
          + id                                     = (known after apply)
          + prefix                                 = (known after apply)
          + tags                                   = (known after apply)

          + expiration {
              + date                         = (known after apply)
              + days                         = (known after apply)
              + expired_object_delete_marker = (known after apply)
            }

          + noncurrent_version_expiration {
              + days = (known after apply)
            }

          + noncurrent_version_transition {
              + days          = (known after apply)
              + storage_class = (known after apply)
            }

          + transition {
              + date          = (known after apply)
              + days          = (known after apply)
              + storage_class = (known after apply)
            }
        }

      + logging {
          + target_bucket = (known after apply)
          + target_prefix = (known after apply)
        }

      + object_lock_configuration {
          + object_lock_enabled = (known after apply)

          + rule {
              + default_retention {
                  + days  = (known after apply)
                  + mode  = (known after apply)
                  + years = (known after apply)
                }
            }
        }

      + replication_configuration {
          + role = (known after apply)

          + rules {
              + delete_marker_replication_status = (known after apply)
              + id                               = (known after apply)
              + prefix                           = (known after apply)
              + priority                         = (known after apply)
              + status                           = (known after apply)

              + destination {
                  + account_id         = (known after apply)
                  + bucket             = (known after apply)
                  + replica_kms_key_id = (known after apply)
                  + storage_class      = (known after apply)

                  + access_control_translation {
                      + owner = (known after apply)
                    }

                  + metrics {
                      + minutes = (known after apply)
                      + status  = (known after apply)
                    }

                  + replication_time {
                      + minutes = (known after apply)
                      + status  = (known after apply)
                    }
                }

              + filter {
                  + prefix = (known after apply)
                  + tags   = (known after apply)
                }

              + source_selection_criteria {
                  + sse_kms_encrypted_objects {
                      + enabled = (known after apply)
                    }
                }
            }
        }

      + server_side_encryption_configuration {
          + rule {
              + bucket_key_enabled = (known after apply)

              + apply_server_side_encryption_by_default {
                  + kms_master_key_id = (known after apply)
                  + sse_algorithm     = (known after apply)
                }
            }
        }

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }

      + website {
          + error_document           = (known after apply)
          + index_document           = (known after apply)
          + redirect_all_requests_to = (known after apply)
          + routing_rules            = (known after apply)
        }
    }

  # aws_s3_bucket_public_access_block.s3-bucket-acl will be created
+ resource "aws_s3_bucket_public_access_block" "s3-bucket-acl" {
      + block_public_acls       = true
      + block_public_policy     = true
      + bucket                  = (known after apply)
      + id                      = (known after apply)
      + ignore_public_acls      = true
      + restrict_public_buckets = true
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ bucket_arn  = (known after apply)
+ bucket_name = "test-terraform-atlantis-workflow-demo-02"

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p bucket`
* :put_litter_in_its_place: To **delete** this plan click [here](http://825d47ad9d61:4141/lock?id=jonasmarquez%252Fatlantis-repo-test%252Fs3%252Fnonprod)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p bucket`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
### 2. project: `instance` dir: `ec2` workspace: `nonprod`
<details><summary>Show Output</summary>

```diff
PLANNING


[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Finding hashicorp/aws versions matching "4.12.1"...
- Finding hashicorp/vault versions matching "3.5.0"...
- Installing hashicorp/aws v4.12.1...
- Installed hashicorp/aws v4.12.1 (signed by HashiCorp)
- Installing hashicorp/vault v3.5.0...
- Installed hashicorp/vault v3.5.0 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.instance-aws will be created
+ resource "aws_instance" "instance-aws" {
      + ami                                  = "ami-042ad9eec03638628"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t2.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = "iac-nonprod"
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = [
          + "sg-0c7d297dfd17a5fac",
        ]
      + source_dest_check                    = true
      + subnet_id                            = "subnet-01ba9a1ea1d1993bb"
      + tags                                 = {
          + "Creator" = "Terraform"
          + "Name"    = "test-terraform-atlantis-ec2-demo"
          + "Team"    = "IAC"
          + "Test"    = "DEMO"
        }
      + tags_all                             = {
          + "Creator" = "Terraform"
          + "Name"    = "test-terraform-atlantis-ec2-demo"
          + "Team"    = "IAC"
          + "Test"    = "DEMO"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id                 = (known after apply)
              + capacity_reservation_resource_group_arn = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + maintenance_options {
          + auto_recovery = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
          + instance_metadata_tags      = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_card_index    = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ instance_id         = (known after apply)
+ instance_name       = "test-terraform-atlantis-ec2-demo"
+ instance_private_ip = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p instance`
* :put_litter_in_its_place: To **delete** this plan click [here](http://825d47ad9d61:4141/lock?id=jonasmarquez%252Fatlantis-repo-test%252Fec2%252Fnonprod)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p instance`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by jonasmarquez — APPROVED** [review]
Ok

**Comment by jonasmarquezkc** [comment]
atlantis apply -p bucket

**Comment by jonasmarquez** [comment]
Ran Apply for project: `bucket` dir: `s3` workspace: `nonprod`

<details><summary>Show Output</summary>

```diff
APPLYING

aws_s3_bucket.s3-bucket: Creating...
aws_s3_bucket.s3-bucket: Creation complete after 1s [id=test-terraform-atlantis-workflow-demo-02]
aws_s3_bucket_public_access_block.s3-bucket-acl: Creating...
aws_s3_bucket_public_access_block.s3-bucket-acl: Creation complete after 0s [id=test-terraform-atlantis-workflow-demo-02]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

bucket_arn = "arn:aws:s3:::test-terraform-atlantis-workflow-demo-02"
bucket_name = "test-terraform-atlantis-workflow-demo-02"

```
</details>

**Comment by jonasmarquez** [comment]
atlantis plan -p bucket

**Comment by jonasmarquez** [comment]
Ran Plan for project: `bucket` dir: `s3` workspace: `nonprod`

<details><summary>Show Output</summary>

```diff
PLANNING


[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of hashicorp/vault from the dependency lock file
- Installing hashicorp/aws v4.12.1...
- Installed hashicorp/aws v4.12.1 (signed by HashiCorp)
- Installing hashicorp/vault v3.5.0...
- Installed hashicorp/vault v3.5.0 (signed by HashiCorp)

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_s3_bucket.s3-bucket has been deleted
- resource "aws_s3_bucket" "s3-bucket" {
      - arn                         = "arn:aws:s3:::test-terraform-atlantis-workflow-demo-02" -> null
      - bucket                      = "test-terraform-atlantis-workflow-demo-02" -> null
      - bucket_domain_name          = "test-terraform-atlantis-workflow-demo-02.s3.amazonaws.com" -> null
      - bucket_regional_domain_name = "test-terraform-atlantis-workflow-demo-02.s3.eu-central-1.amazonaws.com" -> null
      - force_destroy               = false -> null
      - hosted_zone_id              = "Z21DNDUVLTQW6Q" -> null
      - id                          = "test-terraform-atlantis-workflow-demo-02" -> null
      - object_lock_enabled         = false -> null
      - region                      = "eu-central-1" -> null
      - request_payer               = "BucketOwner" -> null
      - tags                        = {
          - "Environment" = "nonprod"
          - "Name"        = "test-terraform-atlantis-workflow-demo-02"
        } -> null
      - tags_all                    = {
          - "Environment" = "nonprod"
          - "Name"        = "test-terraform-atlantis-workflow-demo-02"
        } -> null

      - grant {
          - id          = "a5092fab96ac85482dccd5fdb3c550da761043245b8ae3d1bd9459e24b226dcc" -> null
          - permissions = [
              - "FULL_CONTROL",
            ] -> null
          - type        = "CanonicalUser" -> null
        }

      - versioning {
          - enabled    = false -> null
          - mfa_delete = false -> null
        }
    }

  # aws_s3_bucket_public_access_block.s3-bucket-acl has been deleted
- resource "aws_s3_bucket_public_access_block" "s3-bucket-acl" {
      - block_public_acls       = true -> null
      - block_public_policy     = true -> null
      - bucket                  = "test-terraform-atlantis-workflow-demo-02" -> null
      - id                      = "test-terraform-atlantis-workflow-demo-02" -> null
      - ignore_public_acls      = true -> null
      - restrict_public_buckets = true -> null
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket.s3-bucket will be created
+ resource "aws_s3_bucket" "s3-bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "test-terraform-atlantis-workflow-demo-02"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "Environment" = "nonprod"
          + "Name"        = "test-terraform-atlantis-workflow-demo-02"
        }
      + tags_all                    = {
          + "Environment" = "nonprod"
          + "Name"        = "test-terraform-atlantis-workflow-demo-02"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + cors_rule {
          + allowed_headers = (known after apply)
          + allowed_methods = (known after apply)
          + allowed_origins = (known after apply)
          + expose_headers  = (known after apply)
          + max_age_seconds = (known after apply)
        }

      + grant {
          + id          = (known after apply)
          + permissions = (known after apply)
          + type        = (known after apply)
          + uri         = (known after apply)
        }

      + lifecycle_rule {
          + abort_incomplete_multipart_upload_days = (known after apply)
          + enabled                                = (known after apply)
          + id                                     = (known after apply)
          + prefix                                 = (known after apply)
          + tags                                   = (known after apply)

          + expiration {
              + date                         = (known after apply)
              + days                         = (known after apply)
              + expired_object_delete_marker = (known after apply)
            }

          + noncurrent_version_expiration {
              + days = (known after apply)
            }

          + noncurrent_version_transition {
              + days          = (known after apply)
              + storage_class = (known after apply)
            }

          + transition {
              + date          = (known after apply)
              + days          = (known after apply)
              + storage_class = (known after apply)
            }
        }

      + logging {
          + target_bucket = (known after apply)
          + target_prefix = (known after apply)
        }

      + object_lock_configuration {
          + object_lock_enabled = (known after apply)

          + rule {
              + default_retention {
                  + days  = (known after apply)
                  + mode  = (known after apply)
                  + years = (known after apply)
                }
            }
        }

      + replication_configuration {
          + role = (known after apply)

          + rules {
              + delete_marker_replication_status = (known after apply)
              + id                               = (known after apply)
              + prefix                           = (known after apply)
              + priority                         = (known after apply)
              + status                           = (known after apply)

              + destination {
                  + account_id         = (known after apply)
                  + bucket             = (known after apply)
                  + replica_kms_key_id = (known after apply)
                  + storage_class      = (known after apply)

                  + access_control_translation {
                      + owner = (known after apply)
                    }

                  + metrics {
                      + minutes = (known after apply)
                      + status  = (known after apply)
                    }

                  + replication_time {
                      + minutes = (known after apply)
                      + status  = (known after apply)
                    }
                }

              + filter {
                  + prefix = (known after apply)
                  + tags   = (known after apply)
                }

              + source_selection_criteria {
                  + sse_kms_encrypted_objects {
                      + enabled = (known after apply)
                    }
                }
            }
        }

      + server_side_encryption_configuration {
          + rule {
              + bucket_key_enabled = (known after apply)

              + apply_server_side_encryption_by_default {
                  + kms_master_key_id = (known after apply)
                  + sse_algorithm     = (known after apply)
                }
            }
        }

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }

      + website {
          + error_document           = (known after apply)
          + index_document           = (known after apply)
          + redirect_all_requests_to = (known after apply)
          + routing_rules            = (known after apply)
        }
    }

  # aws_s3_bucket_public_access_block.s3-bucket-acl will be created
+ resource "aws_s3_bucket_public_access_block" "s3-bucket-acl" {
      + block_public_acls       = true
      + block_public_policy     = true
      + bucket                  = (known after apply)
      + id                      = (known after apply)
      + ignore_public_acls      = true
      + restrict_public_buckets = true
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
~ bucket_arn = "arn:aws:s3:::test-terraform-atlantis-workflow-demo-02" -> (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p bucket`
* :put_litter_in_its_place: To **delete** this plan click [here](http://825d47ad9d61:4141/lock?id=jonasmarquez%252Fatlantis-repo-test%252Fs3%252Fnonprod)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p bucket`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by jonasmarquez** [comment]
atlantis unlock

**Comment by jonasmarquez** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Pull request closed without merging**
