### PR TITLE
Test 04

### PR DESCRIPTION
**Pull request by jonasmarquezkc**
Test 04

### CODE REVIEW

**Review by jonasmarquez — APPROVED** [review]
Ok

**Comment by jonasmarquezkc** [comment]
atlantis plan -p bucket

**Comment by jonasmarquez** [comment]
Ran Plan for project: `bucket` dir: `s3` workspace: `nonprod`

<details><summary>Show Output</summary>

```diff
PLANNING


[0m[1mInitializing the backend...[0m
[0m[32m
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Finding hashicorp/aws versions matching "4.12.1"...
- Finding hashicorp/vault versions matching "3.5.0"...
- Installing hashicorp/aws v4.12.1...
- Installed hashicorp/aws v4.12.1 (signed by HashiCorp)
- Installing hashicorp/vault v3.5.0...
- Installed hashicorp/vault v3.5.0 (signed by HashiCorp)

Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket.s3-bucket will be created
+ resource "aws_s3_bucket" "s3-bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "test-terraform-atlantis-workflow-demo-02"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "Environment" = "nonprod"
          + "Name"        = "test-terraform-atlantis-workflow-demo-02"
        }
      + tags_all                    = {
          + "Environment" = "nonprod"
          + "Name"        = "test-terraform-atlantis-workflow-demo-02"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + cors_rule {
          + allowed_headers = (known after apply)
          + allowed_methods = (known after apply)
          + allowed_origins = (known after apply)
          + expose_headers  = (known after apply)
          + max_age_seconds = (known after apply)
        }

      + grant {
          + id          = (known after apply)
          + permissions = (known after apply)
          + type        = (known after apply)
          + uri         = (known after apply)
        }

      + lifecycle_rule {
          + abort_incomplete_multipart_upload_days = (known after apply)
          + enabled                                = (known after apply)
          + id                                     = (known after apply)
          + prefix                                 = (known after apply)
          + tags                                   = (known after apply)

          + expiration {
              + date                         = (known after apply)
              + days                         = (known after apply)
              + expired_object_delete_marker = (known after apply)
            }

          + noncurrent_version_expiration {
              + days = (known after apply)
            }

          + noncurrent_version_transition {
              + days          = (known after apply)
              + storage_class = (known after apply)
            }

          + transition {
              + date          = (known after apply)
              + days          = (known after apply)
              + storage_class = (known after apply)
            }
        }

      + logging {
          + target_bucket = (known after apply)
          + target_prefix = (known after apply)
        }

      + object_lock_configuration {
          + object_lock_enabled = (known after apply)

          + rule {
              + default_retention {
                  + days  = (known after apply)
                  + mode  = (known after apply)
                  + years = (known after apply)
                }
            }
        }

      + replication_configuration {
          + role = (known after apply)

          + rules {
              + delete_marker_replication_status = (known after apply)
              + id                               = (known after apply)
              + prefix                           = (known after apply)
              + priority                         = (known after apply)
              + status                           = (known after apply)

              + destination {
                  + account_id         = (known after apply)
                  + bucket             = (known after apply)
                  + replica_kms_key_id = (known after apply)
                  + storage_class      = (known after apply)

                  + access_control_translation {
                      + owner = (known after apply)
                    }

                  + metrics {
                      + minutes = (known after apply)
                      + status  = (known after apply)
                    }

                  + replication_time {
                      + minutes = (known after apply)
                      + status  = (known after apply)
                    }
                }

              + filter {
                  + prefix = (known after apply)
                  + tags   = (known after apply)
                }

              + source_selection_criteria {
                  + sse_kms_encrypted_objects {
                      + enabled = (known after apply)
                    }
                }
            }
        }

      + server_side_encryption_configuration {
          + rule {
              + bucket_key_enabled = (known after apply)

              + apply_server_side_encryption_by_default {
                  + kms_master_key_id = (known after apply)
                  + sse_algorithm     = (known after apply)
                }
            }
        }

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }

      + website {
          + error_document           = (known after apply)
          + index_document           = (known after apply)
          + redirect_all_requests_to = (known after apply)
          + routing_rules            = (known after apply)
        }
    }

  # aws_s3_bucket_public_access_block.s3-bucket-acl will be created
+ resource "aws_s3_bucket_public_access_block" "s3-bucket-acl" {
      + block_public_acls       = true
      + block_public_policy     = true
      + bucket                  = (known after apply)
      + id                      = (known after apply)
      + ignore_public_acls      = true
      + restrict_public_buckets = true
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
~ bucket_arn = "arn:aws:s3:::test-terraform-atlantis-workflow-demo-02" -> (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p bucket`
* :put_litter_in_its_place: To **delete** this plan click [here](http://825d47ad9d61:4141/lock?id=jonasmarquez%252Fatlantis-repo-test%252Fs3%252Fnonprod)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p bucket`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by jonasmarquezkc** [comment]
atlantis apply -p bucket

**Comment by jonasmarquez** [comment]
Ran Apply for project: `bucket` dir: `s3` workspace: `nonprod`

<details><summary>Show Output</summary>

```diff
APPLYING

aws_s3_bucket.s3-bucket: Creating...
aws_s3_bucket.s3-bucket: Creation complete after 2s [id=test-terraform-atlantis-workflow-demo-02]
aws_s3_bucket_public_access_block.s3-bucket-acl: Creating...
aws_s3_bucket_public_access_block.s3-bucket-acl: Creation complete after 0s [id=test-terraform-atlantis-workflow-demo-02]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

bucket_arn = "arn:aws:s3:::test-terraform-atlantis-workflow-demo-02"
bucket_name = "test-terraform-atlantis-workflow-demo-02"

```
</details>

**Comment by jonasmarquez** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `s3` workspace: `nonprod`

**Pull request merged**
